<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.ParametersAction>
      <safeParameters class="sorted-set"/>
      <parameters>
        <com.cloudbees.plugins.credentials.CredentialsParameterValue plugin="credentials@1502.v5c95e620ddfe">
          <name>Name</name>
          <value></value>
          <isDefaultValue>true</isDefaultValue>
        </com.cloudbees.plugins.credentials.CredentialsParameterValue>
        <hudson.model.TextParameterValue>
          <name>FIRST_NAME</name>
          <value>Joseph</value>
        </hudson.model.TextParameterValue>
        <hudson.model.TextParameterValue>
          <name>SECOND_NAME</name>
          <value>Valencia</value>
        </hudson.model.TextParameterValue>
      </parameters>
      <parameterDefinitionNames>
        <string>Name</string>
        <string>FIRST_NAME</string>
        <string>SECOND_NAME</string>
      </parameterDefinitionNames>
    </hudson.model.ParametersAction>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>admin</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>3</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>1</buildableDurationMillis>
      <waitingDurationMillis>0</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
  </actions>
  <queueId>8</queueId>
  <timestamp>1778301769943</timestamp>
  <startTime>1778301769948</startTime>
  <result>SUCCESS</result>
  <duration>8</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/workspace/miprimerweba</workspace>
  <hudsonVersion>2.563</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>